server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cardtransfer
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: user
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
